### ISSUE TITLE
Part 3c (Saving Data to MongoDB) - add steps to specify environment variables in heroku

### ISSUE THREAD

**Issue by wulforr** [fullstack-hy2020/fullstack-hy2020.github.io#212]
Add the steps for declaring environment variables in heroku as env file is not available on github so it is not present for heroku.

**Comment by wulforr** [comment]
On moving forward with the course I saw that declaring environment variables in heroku is illustrated in part 3d but the app is already hosted on heroku in part 3b so students might deploy their app to heroku after part 3c and run into errors.(my case)
It would be better to illustrate heroku config right next to dotenv package

**Comment by I-keep-trying** [comment]
I came here to suggest this also. I finally got my phonebook app working (using `heroku config:set ENV_VAR=password`)  after several days of frustration and googling, but for some weird reason I did not have the same problem with my notes app. Both databases are side-by-side, in the mongodb "Collections" in the same cluster. Both apps use the same exact versions of everything. 

I did not want to move forward to the next section until I got this part all working. I must have deleted and re-created at least 10 heroku apps. Stackoverflow to the rescue!

**Comment by nikurou** [comment]
I had the same problem because the command given on the course:
`$ heroku config:set MONGODB_URI='mongodb+srv://fullstack:secretpasswordhere@cluster0-ostce.mongodb.net/note-app?retryWrites=true'`
Would simply result in this: 
`»   Error: Missing required flag:
 »     -a, --app APP  app to run command against
 »   See more help with --help
'w' is not recognized as an internal or external command,
operable program or batch file.`

Maybe some things changed with Heroku CLI since the tutorial was written but it took me like 30 minutes to make sense of the error. What ended up working for me was:
 
From the start in case you never set up Heroku CLI....
`$heroku login`
`$heroku apps` //in case you forgot app-name
`$heroku config:set -a your-app-name MONGODB_URI='your_mongoDB_URI'`

**Comment by sahilrajput03** [comment]
Also heroku variables can be set manually via web heroku and that seems much better option to me.
Though command line always wins if you know the command you are looking for.
But if you are willing with website way - its done via going to `Setttings page` and then adding variable there -

![image](https://user-images.githubusercontent.com/31458531/95453443-7c448680-0988-11eb-8a18-50ac685398df.png)
