### ISSUE TITLE
Exercise 3.20 example solution regular expression is too broad

### ISSUE THREAD

**Issue by marcindulak** [fullstack-hy2020/fullstack-hy2020.github.io#2386]
I won't reveal the actual answer, but instead provide an example which illustrates the problem.
In a similar validation rule to the one in the exercise, the following is assumed to evaluate to `false`:

```
node -e 'console.log(/-\w+/.test("+-a+"))'
true
```
The issue is that the beginning and the end of the string are not specified in the regular expression, so it captures too broadly.

**Comment by dev0T** [comment]
Indeed. I just wanted to give some more detail because it might be easier to understand the issue by giving examples that might be used in the current exercise. The given solution will attempt to find the current regex in the whole string. Considering that the first part before the - is supposed to have only two or three numbers as stated, the solution regex returns true for the following examples:

04**077-22334455**
03**03-0404**

The solution is to either add ^ and & to assign the start and the end of the string respectively. Regular expressions are a great topic that wasn't covered in the course, unfortunately.

**Comment by mluukkai** [comment]
is soon fixed
