### ISSUE TITLE
In part0_b , In the "Traditional web applications" section, There is a typo.

### ISSUE THREAD

**Issue by sanketcharanpahadi** [fullstack-hy2020/fullstack-hy2020.github.io#2721]
In the 2nd para, _"The server has formed this document someone."_ should be like _"The server has formed this document somehow."_

**Comment by mayconblopes** [comment]
Please, check if your file is up-to-date, because right now the file [part0b](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/blob/source/src/content/0/en/part0b.md) does not have this issue.

![image](https://user-images.githubusercontent.com/614145/224565806-e5c1e965-f935-454c-9082-8601871de442.png)

Latest commit [3b8873b](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/commit/3b8873b484c6d57e959269464ce08acca4d578c4) 2 weeks ago
