### ISSUE TITLE
Part 1c: Button event prop name does not follow React's suggested convention

### ISSUE THREAD

**Issue by GeoffreyDlvl** [fullstack-hy2020/fullstack-hy2020.github.io#2796]
The Button component uses the name `handleClick` as a prop and later the guide says:
> The event handler is passed to the Button component through the `handleClick` prop. The name of the prop itself is not that significant, but our naming choice wasn't completely random. React's own official [tutorial](https://react.dev/learn/tutorial-tic-tac-toe) suggests this convention.

However, React tutorial recommends naming the prop `on{Event}` and the command handler `handle{Event}`.

**Comment by Overproness** [comment]
Please refer to: [Responding to Events](https://react.dev/learn/responding-to-events)

![image](https://user-images.githubusercontent.com/66616578/233847912-41db3efb-1e78-46d3-91d4-3f0a9e2a44d5.png)

This is the second example on the page. And it uses the same naming convention as used by the course.

**Comment by KartikAroraOfficial** [comment]
Hi, I've reviewed the site and it seems okay to me. It's following the best practices itself, please reach out with proper references if there's still any doubt or if you think something's been overlooked.

**Comment by GeoffreyDlvl** [comment]
Hi, my comment was more specifically referring to the `Button` component, which is implemented as follow in the guide:

<img width="1039" alt="Screenshot 2023-10-30 at 14 09 27" src="https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/31706682/6c83e76a-9e81-4a6f-8363-6bff9c82094b">

Here the prop is called `handleClick`. In the same page @Overproness provided ([Responding to Events](https://react.dev/learn/responding-to-events)) another example lower in the page gives the following implementation for `Button`:
<img width="1086" alt="Screenshot 2023-10-30 at 14 07 16" src="https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/31706682/2ce87260-e26e-45c8-a823-761df4ad2543">

In the documentation, the prop is named `onClick`. As a consequence, when using the component, the prop of the `Button` component is `onClick` (as can be seens in the screenshot above).

In the course, because of how we named the `Button` prop, we use the button component as follow (using `handleClick` prop instead of `onClick`):
<img width="1021" alt="Screenshot 2023-10-30 at 14 09 46" src="https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/31706682/2aab9c3c-1043-4581-94dd-006a9b7313e7">

**Comment by KartikAroraOfficial** [comment]
In [Naming event handler props](https://react.dev/learn/tutorial-tic-tac-toe)
> Naming event handler props 
Built-in components like <button> and <div> only support [browser event names](https://react.dev/reference/react-dom/components/common#common-props) like onClick. However, when you’re building your own components, you can name their event handler props any way that you like.
By convention, event handler props should start with on, followed by a capital letter.
For example, the Button component’s onClick prop could have been called onSmash:

> ![image](https://github.com/fullstack-hy2020/fullstack-hy2020.github.io/assets/90651659/5da5f29a-9a04-4cbc-ae88-0664afcb2908)

So, all in all when defining your props for a custom component, you'd use this, otherwise, while initializing your components, you'd name the event handlers as `handle${event}` where `${event}` refers to the event name eg. handleClick, handleSubmit etc.

The same could be found in the react tutorial link above 

> By convention, it is common to name event handlers as handle followed by the event name. You’ll often see onClick={handleClick}, onMouseEnter={handleMouseEnter}, and so on.

Appropriate changes to the repo would be made ASAP.
