### ISSUE TITLE
In Part1, Command to remove .git folder doesn't work on Windows

### ISSUE THREAD

**Issue by PersianBlue** [fullstack-hy2020/fullstack-hy2020.github.io#3028]
We're told that create-react-app automatically creates a git repository, and since we don't want a new one each time we should remove it with the command rm -rf .git . However, this apparently works on Linux but not on Windows. The appropriate command to get the same result is to run rmdir /s /q .git  (the /s is to remove all subdirectories, and the /q is to remove the folder quietly, without asking for confirmation).

**Comment by bambery** [comment]
This entire course is going to assume you are running in a *nix environment and not powershell or other windows environments. I would think this course is not going to be possible otherwise. I think you'll have to rely on our old friend WSL2 for running a *nix env in windows to complete this course.

**Comment by mluukkai** [comment]
use of vite deprecates this issue
