### ISSUE TITLE
Chapter on CSS

### ISSUE THREAD

**Issue by avdb13** [fullstack-hy2020/fullstack-hy2020.github.io#3197]
First of all, hank you very much for providing this course as I found it to be more straight-to-the-point than most available on the internet.
However, I think it's necessary to provide a chapter on CSS since this is a struggle for even the most experienced developer. It could cover the cascade, inheritance, selectors, flexbox/grid, specificity and sizing units. I feel like this could fit before chapter 7, focusing on how we can build layouts for an existing project made in previous projects.
Let me know if anybody is interesting in tackling this with me.

**Comment by KartikAroraOfficial** [comment]
I think this is a good point and should be considered. But for the time being, there is [odin project](https://www.theodinproject.com/lessons/foundations-intro-to-css) for CSS, you can start from the link provided and go up to the landing page project, I'm assuming you have prior basic HTML knowledge since you're taking this course and there are other resources such as [w3schools](https://www.w3schools.com/css/default.asp) which provides a bit more discretion and depth into it and for practicing there is [cssbattle.dev](https://cssbattle.dev/) that I'd recommend. But if you want a really good and deep and clear understanding I'd recommend MDN's front-end developer course. You can start with [CSS](https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer#styling_and_layout_with_css) part, it also has quite some exercises so it's good for learning.  This is something that if someone does along with practicing on [cssbattle.dev](https://cssbattle.dev/) they don't really need to look left or right before doing much of the stuff. They've reached an intermediate  or above intermediate level after doing this. Rest is again dependent on practice.

**Comment by avdb13** [comment]
Wanna write a chapter on CSS with me?

**Comment by nahomsisa** [comment]
i know i am late to answer this, but i am ready now, could you update with me?

**Comment by avdb13** [comment]
@nahomsisa I initially planned this as a way to learn through explaining something in my own words but @KartikDotDev already provided pretty much a comprehensive answer. My personal pick for learning CSS ended up being https://web.dev .
