### ISSUE TITLE
5b Critique: Students should reap the benefit of following instructor's lead

### ISSUE THREAD

**Issue by waciumawanjohi** [fullstack-hy2020/fullstack-hy2020.github.io#466]
[Lesson 5b](https://fullstackopen.com/en/part5/props_children_and_proptypes) introduces a pattern to create reusable components that wrap child components, in particular a _Toggleable_ component.

Excercise 5.5 encourages students to use the Toggleable component. As with most coding that is meant to be robust and reusable, this approach is more involved.

Exercise 5.7 is written in a manner that makes the investment in reuseable code worthless. From the course text, "even though the functionality implemented in this part is almost identical to the functionality provided by the Togglable component, the component can not be used directly to achieve the desired behavior."

**Comment by sahilrajput03** [comment]
How it should be?, can you provide some example? I myself noticed the togglable component and the very particular clicking the inside of the child component with the parent component, and that's not easy to maintain. If you could provide with some better code it could be helpful for the course too.

**Comment by waciumawanjohi** [comment]
My argument is that students should be able to implement Exercise 5.7 with Toggleable. In order for that to occur, the instructor would need to slightly change the requirements of Exercise 5.7.

**Comment by sahilrajput03** [comment]
But, I don't you think states are a better way to control the togglability of anycomponent, I mean we can simply make use o if block to toggle any 2nd child component of any child component like we used to do earlier, even in togglability it can be done via providing the state and the corresponding setState method to the child component which is initialized in the main component. And based on any click or we can simply change the state to true or false to hide or show it.
Wouln't that approach be much simpler to define the visibility state of anything? Also, since its present in top component it would be accessible from everywhere, when passed as props to the children?

**Comment by mluukkai** [comment]
closing this since it is intentional that exercises have variation on the theory
