### ISSUE TITLE
Part 2.14*: Data for countries, step3

### ISSUE THREAD

**Issue by lansinq** [fullstack-hy2020/fullstack-hy2020.github.io#745]
What's the point in saving API key to .env file? Looking at my network requests the key still shows up so it's basically just being copy & pasted from it.

**Comment by Kaltsoon** [comment]
It's generally a good practice to use environment variables in cases where you want to use different configurations based on the environment. In this case, you might want to use a different API key in the development environment than in the production environment. `.env` files are just a convenient way to pass environment variables vs. passing them inline in the build command.

> Looking at my network requests the key still shows up so it's basically just being copy & pasted from it.

Sure it is. At runtime, the environment variable acts just like any other variable. The point is that you want to use constants instead of hard-coded values in your code.
